excluded:
  - .build
  - Build
  - Carthage
  - DerivedData
  - Pods

disabled_rules:
  - function_parameter_count
  - identifier_name
  - line_length
  - multiple_closures_with_trailing_closure
  - nesting
  - todo
  - type_name

opt_in_rules:
  - closure_body_length
  - empty_string
  - fallthrough
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - legacy_objc_type
  - override_in_extension
  - redundant_nil_coalescing
  - static_operator
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - weak_delegate

# force warnings
force_cast: error
force_try: error 

custom_rules:
  commented_out_code: 
    included: .*\.swift # regex that defines paths to include during linting. optional.
    excluded: .*Test(s)?\.swift # regex that defines paths to exclude during linting. optional
    name: Commented out code # rule name. optional.
    regex: ^\s*(\/\/(?!\s*swiftlint:).*|\/\*[\s\S]*?\*\/) # matching pattern
    capture_group: 0 # number of regex capture group to highlight the rule violation at. optional.
    match_kinds: # SyntaxKinds to match. optional.
      - comment
    message: No commented code in devel branch allowed. # violation message. optional.
    severity: warning # violation severity. optional.
